### ISSUE TITLE
Anonymizer leaves traces of name in string fields

### ISSUE THREAD

**Issue by dgobbi** [njvack/pfile-tools#2]
For c_char_Array fields, such as "patient_name",  setting a new value does not completely erase the old value.  Here is a quick example of the problematic behavior of the ctypes.Structure class:

    import ctypes
    
    class header(ctypes.LittleEndianStructure):
        _fields_ = [('patient_name', ctypes.c_char * 33)]
    
    h = header()
    h.patient_name = u'Jason James Wachowski'.encode('ascii')
    # anonymize
    h.patient_name = u'ANONYMIZED'.encode('ascii')
    print(repr(h.patient_name))
    'ANONYMIZED'
    print(repr(memoryview(h).tobytes()))
    'ANONYMIZED\x00 Wachowski\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

As shown above, part of the name is still present.  It is hidden behind a null byte, but it becomes visible in a binary dump of the pfile.  It is also visible if the pfile is read into matlab, which is how we first discovered this issue.

**Comment by dgobbi** [comment]
Here is a roundabout way to clear the field completely, leaving no residue:

    def clear_char_array(header, field):
        field = getattr(type(header), field)
        fieldtype = ctypes.c_char*field.size
        fieldtype.from_buffer(header, field.offset).raw = b'\0'*field.size
    
    # example usage
    clear_char_array(h, 'patient_name')

**Comment by njvack** [comment]
Yeah -- explicitly nulling the fields (there shouldn't be any particular problem nulling out an int or float field, should there?) as part of set_struct_value() sounds like a very solid idea. Thanks for finding this.

I know this should be a pretty small amount of code, but I'm not certain when I'd get time to write it. Would you be willing to do this (and test it out) and submit a PR?

**Comment by dgobbi** [comment]
I've submitted a PR that contains the code that we're currently using (it's tested).
